# Generated by Django 6.0.7 on 2026-07-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0002_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie en m²', max_digits=8)),
                ('services', models.CharField(blank=True, max_length=200)),
                ('nombre_employes', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['nom'],
            },
        ),
    ]
