# Generated by Django 6.0.7 on 2026-07-22 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0003_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('capacite_total', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parking',
                'verbose_name_plural': 'Parkings',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PlaceParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée')], default='libre', max_length=20)),
                ('type_place', models.CharField(blank=True, max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='parc.parking')),
            ],
            options={
                'verbose_name': 'Place de parking',
                'verbose_name_plural': 'Places de parking',
                'ordering': ['parking__nom', 'numero'],
                'unique_together': {('parking', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='parc.poste')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('place_parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='parc.placeparking')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='parc.utilisateur')),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'Occupations',
                'ordering': ['-date_entree'],
            },
        ),
    ]
