# Generated by Django 6.0.7 on 2026-07-29 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0005_utilisateur_personnel_obligatoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='personnel',
            field=models.OneToOneField(help_text="L'utilisateur doit être un membre du personnel déjà enregistré.", on_delete=django.db.models.deletion.PROTECT, related_name='compte_utilisateur', to='parc.personnel', verbose_name='Personnel'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
    ]
