# Generated by Django 6.0.7 on 2026-07-30 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0008_placeparking_poste_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='capacite_total',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
