# Generated by Django 6.0.7 on 2026-07-31 08:13

from django.db import migrations, models


def marquer_postes_chauffeur(apps, schema_editor):
    Poste = apps.get_model("parc", "Poste")
    for poste in Poste.objects.all():
        if poste.nom.strip().lower() == "chauffeur":
            poste.est_chauffeur = True
            poste.save(update_fields=["est_chauffeur"])


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0013_conducteurs_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='est_chauffeur',
            field=models.BooleanField(default=False, help_text='Cocher pour le poste de chauffeur (personnel affectable comme chauffeur de véhicule).'),
        ),
        migrations.RunPython(marquer_postes_chauffeur, migrations.RunPython.noop),
    ]
