# Generated by Django 6.0.7 on 2026-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
